name: Bun CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1

      - name: Install Dependencies
        run: |
          bun install --frozen-lockfile
          bun run build-storybook
          cd storybook-static
          touch .nojekyll
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
        env:
          CI: true